version : '3.8'

volumes:
  static:

services:

  backend:
    build:
      context: ./bot_backend
    container_name: nuts-bot-backend
    volumes:
      - ./bot_backend/:/app/
      - static:/app/static
    ports:
      - "8000:8000"
    command:
      - run_django

  bot:
    build:
      context: ./bot_backend
    container_name: nuts-bot-bot
    volumes:
      - ./bot_backend/:/app/
    command: run_bot

  nginx:
    build:
      context: ./nginx
    container_name: nuts-bot-nginx
    depends_on:
      - backend
    ports:
      - "80:7000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/static