# Generated by Django 4.0.4 on 2022-12-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='media/photos/products', verbose_name='Фото'),
        ),
    ]
