# Generated by Django 4.0.4 on 2022-12-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_orderproduct_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_refused',
            field=models.BooleanField(default=False, verbose_name='Заказ отменен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Заказ успешно завершен'),
        ),
    ]
