# Generated by Django 4.0.4 on 2022-12-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_orderproduct_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/products', verbose_name='Фото'),
        ),
    ]
